[package]
name = "rusgit"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"
sha1 = "0.10"
flate2 = "1.0"
hex = "0.4"
byteorder = "1.4"